# language: pt
Funcionalidade: Importar uma lista de disciplinas do site SIGAA

    Enquanto administrador,
    Para adicionar disciplinas pertencentes ao departamento CIC ao banco de dados,
    Eu quero importar uma lista de disciplinas a partir de uma página Html.

Cenário de Fundo:
    Dado que o banco possui um adminstrador
    E que o "admin" está logado
    E que eu estou na página de importar disciplinas

Cenário: Disciplinas importadas corretamente
    Dado que eu coloco o arquivo "turmas_test_happy.html" em "arquivo_turmas"
    Quando eu clico em "Importar disciplinas"
    Então eu devo estar na página de importar disciplinas
    E eu devo ver "Disciplinas importadas com sucesso!"
    E eu devo ver:
    |ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES|
    |ARQUITETURA DE PROCESSADORES DIGITAIS|
    |ARQUITETURAS AVANCADAS|
    |AUTÔMATOS E COMPUTABILIDADE|
    |BANCOS DE DADOS|
    |CIRCUITOS LÓGICOS|
    |COMPUTAÇÃO EXPERIMENTAL|
    |DESENVOLVIMENTO DE APLICATIVOS|
    |ENGENHARIA DE SOFTWARE|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 1|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 2|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 1|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 2|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 3|
    |ESTRUTURAS DE DADOS|
    |ESTUDOS EM COMPUTACAO MULTIMIDIA|
    |ESTUDOS EM INTELIGENCIA ARTIFICIAL|
    |ESTUDOS EM SISTEMAS DE COMPUTACAO|
    |ESTUDOS EM SISTEMAS DE INFORMACAO|
    |FORMAÇÃO DOCENTE EM COMPUTAÇÃO|
    |FUNDAMENTOS TEÓRICOS DA COMPUTAÇÃO|
    |INFORMATICA APLICADA A EDUCACAO|
    |INFORMATICA E SOCIEDADE|
    |INTERAÇÃO HUMANO COMPUTADOR|
    |INTRODUÇÃO À CIÊNCIA DA COMPUTAÇÃO|
    |INTRODUÇÃO À ENGENHARIA DE COMPUTAÇÃO|
    |INTRODUCAO A INTELIGENCIA ARTIFICIAL|
    |INTRODUCAO A MICROINFORMATICA|
    |INTRODUCAO AO PROCESSAMENTO DE IMAGENS|
    |INTRODUÇÃO AOS SISTEMAS COMPUTACIONAIS|
    |INTRODUÇÃO AOS SISTEMAS EMBARCADOS|
    |INTRODUÇÃO A SISTEMAS OPERACIONAIS|
    |LABORATÓRIO DE CIRCUITOS LÓGICOS|
    |LINGUAGENS DE PROGRAMACAO|
    |LÓGICA COMPUTACIONAL 1|
    |METODOLOGIA CIENTÍFICA|
    |MÉTODOS DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|
    |MÉTODOS DE PROGRAMAÇÃO|
    |ORGANIZAÇÃO E ARQUITETURA DE COMPUTADORES|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|
    |PRÁTICAS EM COMPUTAÇÃO|
    |PRINCÍPIOS DE VISÃO COMPUTACIONAL|
    |PROCESSAMENTO DE SINAIS MULTIMÍDIA|
    |PROCESSAMENTO EM TEMPO REAL|
    |PRODUÇÃO CIENTIFICA NA LICENCIATURA EM COMPUTAÇÃO|
    |PRODUÇÃO DE MATERIAL DIDÁTICO|
    |PROGRAMAÇÃO COMPETITIVA|
    |PROGRAMAÇÃO CONCORRENTE|
    |PROJETO DE LICENCIATURA|
    |PROJETO DE LICENCIATURA 1|
    |PROJETO DE LICENCIATURA 2|
    |PROJETO DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|
    |PROJETO E ANÁLISE DE ALGORITMOS|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 1|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 2|
    |PROJETO INTERDISCIPLINAR DE LICENCIATURA EM COMPUTAÇÃO|
    |REDES DE COMPUTADORES|
    |SEGURANÇA COMPUTACIONAL|
    |SINAIS E SISTEMAS|
    |SISTEMAS DE INFORMACAO|
    |SISTEMAS OPERACIONAIS|
    |SOFTWARE BASICO|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|
    |SUPERVISÃO DE PRODUÇÃO DE MATERIAL DIDÁTICO|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 1|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 2|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 3|
    |TECNICAS DE PROGRAMAÇÃO 1|
    |TECNICAS DE PROGRAMAÇÃO 2|
    |TELEINFORMÁTICA E REDES 1|
    |TELEINFORMÁTICA E REDES 2|
    |TEORIA DA COMPUTACAO|
    |TEORIA E APLICAÇÃO DE GRAFOS|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 1|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 2|
    |TOPICOS AVANCADOS EM COMPUTADORES|
    |TRABALHO DE GRADUAÇÃO 1|
    |TRABALHO DE GRADUAÇÃO 2|
    |TRADUTORES|
    |TRANSMISSÃO DE DADOS|
    |VISUALIZAÇÃO DE DADOS|

Cenário: Há erro na formatação da página remota
    Dado que eu coloco o arquivo "turmas_test_sad.html" em "arquivo_turmas"
    Quando eu clico em "Importar disciplinas"
    Então eu devo ver "Erro: Erro de formatação"

Cenário: Disciplinas já existem
    Dado que as seguintes disciplinas existem:
    |nome|
    |ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES|
    |ARQUITETURA DE PROCESSADORES DIGITAIS|
    |ARQUITETURAS AVANCADAS|
    |AUTÔMATOS E COMPUTABILIDADE|
    |BANCOS DE DADOS|
    |CIRCUITOS LÓGICOS|
    |COMPUTAÇÃO EXPERIMENTAL|
    |DESENVOLVIMENTO DE APLICATIVOS|
    |ENGENHARIA DE SOFTWARE|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 1|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 2|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 1|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 2|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 3|
    |ESTRUTURAS DE DADOS|
    |ESTUDOS EM COMPUTACAO MULTIMIDIA|
    |ESTUDOS EM INTELIGENCIA ARTIFICIAL|
    |ESTUDOS EM SISTEMAS DE COMPUTACAO|
    |ESTUDOS EM SISTEMAS DE INFORMACAO|
    |FORMAÇÃO DOCENTE EM COMPUTAÇÃO|
    |FUNDAMENTOS TEÓRICOS DA COMPUTAÇÃO|
    |INFORMATICA APLICADA A EDUCACAO|
    |INFORMATICA E SOCIEDADE|
    |INTERAÇÃO HUMANO COMPUTADOR|
    |INTRODUÇÃO À CIÊNCIA DA COMPUTAÇÃO|
    |INTRODUÇÃO À ENGENHARIA DE COMPUTAÇÃO|
    |INTRODUCAO A INTELIGENCIA ARTIFICIAL|
    |INTRODUCAO A MICROINFORMATICA|
    |INTRODUCAO AO PROCESSAMENTO DE IMAGENS|
    |INTRODUÇÃO AOS SISTEMAS COMPUTACIONAIS|
    |INTRODUÇÃO AOS SISTEMAS EMBARCADOS|
    |INTRODUÇÃO A SISTEMAS OPERACIONAIS|
    |LABORATÓRIO DE CIRCUITOS LÓGICOS|
    |LINGUAGENS DE PROGRAMACAO|
    |LÓGICA COMPUTACIONAL 1|
    |METODOLOGIA CIENTÍFICA|
    |MÉTODOS DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|
    |MÉTODOS DE PROGRAMAÇÃO|
    |ORGANIZAÇÃO E ARQUITETURA DE COMPUTADORES|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|
    |PRÁTICAS EM COMPUTAÇÃO|
    |PRINCÍPIOS DE VISÃO COMPUTACIONAL|
    |PROCESSAMENTO DE SINAIS MULTIMÍDIA|
    |PROCESSAMENTO EM TEMPO REAL|
    |PRODUÇÃO CIENTIFICA NA LICENCIATURA EM COMPUTAÇÃO|
    |PRODUÇÃO DE MATERIAL DIDÁTICO|
    |PROGRAMAÇÃO COMPETITIVA|
    |PROGRAMAÇÃO CONCORRENTE|
    |PROJETO DE LICENCIATURA|
    |PROJETO DE LICENCIATURA 1|
    |PROJETO DE LICENCIATURA 2|
    |PROJETO DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|
    |PROJETO E ANÁLISE DE ALGORITMOS|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 1|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 2|
    |PROJETO INTERDISCIPLINAR DE LICENCIATURA EM COMPUTAÇÃO|
    |REDES DE COMPUTADORES|
    |SEGURANÇA COMPUTACIONAL|
    |SINAIS E SISTEMAS|
    |SISTEMAS DE INFORMACAO|
    |SISTEMAS OPERACIONAIS|
    |SOFTWARE BASICO|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|
    |SUPERVISÃO DE PRODUÇÃO DE MATERIAL DIDÁTICO|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 1|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 2|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 3|
    |TECNICAS DE PROGRAMAÇÃO 1|
    |TECNICAS DE PROGRAMAÇÃO 2|
    |TELEINFORMÁTICA E REDES 1|
    |TELEINFORMÁTICA E REDES 2|
    |TEORIA DA COMPUTACAO|
    |TEORIA E APLICAÇÃO DE GRAFOS|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 1|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 2|
    |TOPICOS AVANCADOS EM COMPUTADORES|
    |TRABALHO DE GRADUAÇÃO 1|
    |TRABALHO DE GRADUAÇÃO 2|
    |TRADUTORES|
    |TRANSMISSÃO DE DADOS|
    |VISUALIZAÇÃO DE DADOS|

    E que eu coloco o arquivo "turmas_test_happy.hmtl" em "arquivo_turmas"
    Quando eu clico em "Importar disciplinas"
    Então eu devo estar na página de importar disciplinas
    E eu devo ver "Aviso: Uma ou mais disciplinas já estão presentes no banco de dados"
    E eu devo ver os seguintes itens somente uma vez:
    |ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES|
    |ARQUITETURA DE PROCESSADORES DIGITAIS|
    |ARQUITETURAS AVANCADAS|
    |AUTÔMATOS E COMPUTABILIDADE|
    |BANCOS DE DADOS|
    |CIRCUITOS LÓGICOS|
    |COMPUTAÇÃO EXPERIMENTAL|
    |DESENVOLVIMENTO DE APLICATIVOS|
    |ENGENHARIA DE SOFTWARE|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 1|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 2|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 1|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 2|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 3|
    |ESTRUTURAS DE DADOS|
    |ESTUDOS EM COMPUTACAO MULTIMIDIA|
    |ESTUDOS EM INTELIGENCIA ARTIFICIAL|
    |ESTUDOS EM SISTEMAS DE COMPUTACAO|
    |ESTUDOS EM SISTEMAS DE INFORMACAO|
    |FORMAÇÃO DOCENTE EM COMPUTAÇÃO|
    |FUNDAMENTOS TEÓRICOS DA COMPUTAÇÃO|
    |INFORMATICA APLICADA A EDUCACAO|
    |INFORMATICA E SOCIEDADE|
    |INTERAÇÃO HUMANO COMPUTADOR|
    |INTRODUÇÃO À CIÊNCIA DA COMPUTAÇÃO|
    |INTRODUÇÃO À ENGENHARIA DE COMPUTAÇÃO|
    |INTRODUCAO A INTELIGENCIA ARTIFICIAL|
    |INTRODUCAO A MICROINFORMATICA|
    |INTRODUCAO AO PROCESSAMENTO DE IMAGENS|
    |INTRODUÇÃO AOS SISTEMAS COMPUTACIONAIS|
    |INTRODUÇÃO AOS SISTEMAS EMBARCADOS|
    |INTRODUÇÃO A SISTEMAS OPERACIONAIS|
    |LABORATÓRIO DE CIRCUITOS LÓGICOS|
    |LINGUAGENS DE PROGRAMACAO|
    |LÓGICA COMPUTACIONAL 1|
    |METODOLOGIA CIENTÍFICA|
    |MÉTODOS DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|
    |MÉTODOS DE PROGRAMAÇÃO|
    |ORGANIZAÇÃO E ARQUITETURA DE COMPUTADORES|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|
    |PRÁTICAS EM COMPUTAÇÃO|
    |PRINCÍPIOS DE VISÃO COMPUTACIONAL|
    |PROCESSAMENTO DE SINAIS MULTIMÍDIA|
    |PROCESSAMENTO EM TEMPO REAL|
    |PRODUÇÃO CIENTIFICA NA LICENCIATURA EM COMPUTAÇÃO|
    |PRODUÇÃO DE MATERIAL DIDÁTICO|
    |PROGRAMAÇÃO COMPETITIVA|
    |PROGRAMAÇÃO CONCORRENTE|
    |PROJETO DE LICENCIATURA|
    |PROJETO DE LICENCIATURA 1|
    |PROJETO DE LICENCIATURA 2|
    |PROJETO DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|
    |PROJETO E ANÁLISE DE ALGORITMOS|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 1|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 2|
    |PROJETO INTERDISCIPLINAR DE LICENCIATURA EM COMPUTAÇÃO|
    |REDES DE COMPUTADORES|
    |SEGURANÇA COMPUTACIONAL|
    |SINAIS E SISTEMAS|
    |SISTEMAS DE INFORMACAO|
    |SISTEMAS OPERACIONAIS|
    |SOFTWARE BASICO|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|
    |SUPERVISÃO DE PRODUÇÃO DE MATERIAL DIDÁTICO|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 1|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 2|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 3|
    |TECNICAS DE PROGRAMAÇÃO 1|
    |TECNICAS DE PROGRAMAÇÃO 2|
    |TELEINFORMÁTICA E REDES 1|
    |TELEINFORMÁTICA E REDES 2|
    |TEORIA DA COMPUTACAO|
    |TEORIA E APLICAÇÃO DE GRAFOS|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 1|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 2|
    |TOPICOS AVANCADOS EM COMPUTADORES|
    |TRABALHO DE GRADUAÇÃO 1|
    |TRABALHO DE GRADUAÇÃO 2|
    |TRADUTORES|
    |TRANSMISSÃO DE DADOS|
    |VISUALIZAÇÃO DE DADOS|