# language: pt
Funcionalidade: Importar uma lista de disciplinas do site SIGAA

    Enquanto administrador,
    Para adicionar disciplinas pertencentes ao departamento CIC ao banco de dados,
    Eu quero importar uma lista de disciplinas a partir de uma página Html.

Cenário de Fundo:
    Dado que o banco possui um adminstrador
    E que o "admin" está logado
    E que eu estou na página de importar disciplinas

Cenário: Disciplinas importadas corretamente
    Dado que eu coloco o arquivo "features/files/turmas_test_happy.html" em "arquivo_turmas"
    Quando eu aperto em "Importar disciplinas"
    Então eu devo estar na página de importar disciplinas
    E eu devo ver "Disciplinas importadas com sucesso!"
    E eu devo ver:
    |ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES|
    |ARQUITETURA DE PROCESSADORES DIGITAIS|
    |ARQUITETURAS AVANCADAS|
    |AUTÔMATOS E COMPUTABILIDADE|
    |BANCOS DE DADOS|
    |CIRCUITOS LÓGICOS|
    |COMPUTAÇÃO EXPERIMENTAL|
    |DESENVOLVIMENTO DE APLICATIVOS|
    |ENGENHARIA DE SOFTWARE|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 1|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 2|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 1|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 2|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 3|
    |ESTRUTURAS DE DADOS|
    |ESTUDOS EM COMPUTACAO MULTIMIDIA|
    |ESTUDOS EM INTELIGENCIA ARTIFICIAL|
    |ESTUDOS EM SISTEMAS DE COMPUTACAO|
    |ESTUDOS EM SISTEMAS DE INFORMACAO|
    |FORMAÇÃO DOCENTE EM COMPUTAÇÃO|
    |FUNDAMENTOS TEÓRICOS DA COMPUTAÇÃO|
    |INFORMATICA APLICADA A EDUCACAO|
    |INFORMATICA E SOCIEDADE|
    |INTERAÇÃO HUMANO COMPUTADOR|
    |INTRODUÇÃO À CIÊNCIA DA COMPUTAÇÃO|
    |INTRODUÇÃO À ENGENHARIA DE COMPUTAÇÃO|
    |INTRODUCAO A INTELIGENCIA ARTIFICIAL|
    |INTRODUCAO A MICROINFORMATICA|
    |INTRODUCAO AO PROCESSAMENTO DE IMAGENS|
    |INTRODUÇÃO AOS SISTEMAS COMPUTACIONAIS|
    |INTRODUÇÃO AOS SISTEMAS EMBARCADOS|
    |INTRODUÇÃO A SISTEMAS OPERACIONAIS|
    |LABORATÓRIO DE CIRCUITOS LÓGICOS|
    |LINGUAGENS DE PROGRAMACAO|
    |LÓGICA COMPUTACIONAL 1|
    |METODOLOGIA CIENTÍFICA|
    |MÉTODOS DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|
    |MÉTODOS DE PROGRAMAÇÃO|
    |ORGANIZAÇÃO E ARQUITETURA DE COMPUTADORES|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|
    |PRÁTICAS EM COMPUTAÇÃO|
    |PRINCÍPIOS DE VISÃO COMPUTACIONAL|
    |PROCESSAMENTO DE SINAIS MULTIMÍDIA|
    |PROCESSAMENTO EM TEMPO REAL|
    |PRODUÇÃO CIENTIFICA NA LICENCIATURA EM COMPUTAÇÃO|
    |PRODUÇÃO DE MATERIAL DIDÁTICO|
    |PROGRAMAÇÃO COMPETITIVA|
    |PROGRAMAÇÃO CONCORRENTE|
    |PROJETO DE LICENCIATURA|
    |PROJETO DE LICENCIATURA 1|
    |PROJETO DE LICENCIATURA 2|
    |PROJETO DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|
    |PROJETO E ANÁLISE DE ALGORITMOS|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 1|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 2|
    |PROJETO INTERDISCIPLINAR DE LICENCIATURA EM COMPUTAÇÃO|
    |REDES DE COMPUTADORES|
    |SEGURANÇA COMPUTACIONAL|
    |SINAIS E SISTEMAS|
    |SISTEMAS DE INFORMACAO|
    |SISTEMAS OPERACIONAIS|
    |SOFTWARE BASICO|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|
    |SUPERVISÃO DE PRODUÇÃO DE MATERIAL DIDÁTICO|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 1|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 2|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 3|
    |TECNICAS DE PROGRAMAÇÃO 1|
    |TECNICAS DE PROGRAMAÇÃO 2|
    |TELEINFORMÁTICA E REDES 1|
    |TELEINFORMÁTICA E REDES 2|
    |TEORIA DA COMPUTACAO|
    |TEORIA E APLICAÇÃO DE GRAFOS|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 1|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 2|
    |TOPICOS AVANCADOS EM COMPUTADORES|
    |TRABALHO DE GRADUAÇÃO 1|
    |TRABALHO DE GRADUAÇÃO 2|
    |TRADUTORES|
    |TRANSMISSÃO DE DADOS|
    |VISUALIZAÇÃO DE DADOS|

Cenário: Disciplinas já existem
    Dado que as seguintes disciplinas existem:
    |nome|cod_disciplina|
    |ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES|CIC0004|
    |ARQUITETURA DE PROCESSADORES DIGITAIS|CIC0177|
    |ARQUITETURAS AVANCADAS|CIC0121|
    |AUTÔMATOS E COMPUTABILIDADE|CIC0161|
    |BANCOS DE DADOS|CIC0097|
    |CIRCUITOS LÓGICOS|CIC0229|
    |COMPUTAÇÃO EXPERIMENTAL|CIC0203|
    |DESENVOLVIMENTO DE APLICATIVOS|CIC0226|
    |ENGENHARIA DE SOFTWARE|CIC0105|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 1|CIC0246|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 2|CIC0243|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 1|CIC0214|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 2|CIC0215|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 3|CIC0216|
    |ESTRUTURAS DE DADOS|CIC0090|
    |ESTUDOS EM COMPUTACAO MULTIMIDIA|CIC0116|
    |ESTUDOS EM INTELIGENCIA ARTIFICIAL|CIC0136|
    |ESTUDOS EM SISTEMAS DE COMPUTACAO|CIC0132|
    |ESTUDOS EM SISTEMAS DE INFORMACAO|CIC0143|
    |FORMAÇÃO DOCENTE EM COMPUTAÇÃO|CIC0005|
    |FUNDAMENTOS TEÓRICOS DA COMPUTAÇÃO|CIC0002|
    |INFORMATICA APLICADA A EDUCACAO|CIC0158|
    |INFORMATICA E SOCIEDADE|CIC0142|
    |INTERAÇÃO HUMANO COMPUTADOR|CIC0194|
    |INTRODUÇÃO À CIÊNCIA DA COMPUTAÇÃO|CIC0007|
    |INTRODUÇÃO À ENGENHARIA DE COMPUTAÇÃO|CIC0188|
    |INTRODUCAO A INTELIGENCIA ARTIFICIAL|CIC0135|
    |INTRODUCAO A MICROINFORMATICA|CIC0152|
    |INTRODUCAO AO PROCESSAMENTO DE IMAGENS|CIC0176|
    |INTRODUÇÃO AOS SISTEMAS COMPUTACIONAIS|CIC0003|
    |INTRODUÇÃO AOS SISTEMAS EMBARCADOS|CIC0130|
    |INTRODUÇÃO A SISTEMAS OPERACIONAIS|CIC0225|
    |LABORATÓRIO DE CIRCUITOS LÓGICOS|CIC0231|
    |LINGUAGENS DE PROGRAMACAO|CIC0093|
    |LÓGICA COMPUTACIONAL 1|CIC0182|
    |METODOLOGIA CIENTÍFICA|CIC0200|
    |MÉTODOS DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|CIC0206|
    |MÉTODOS DE PROGRAMAÇÃO|CIC0234|
    |ORGANIZAÇÃO E ARQUITETURA DE COMPUTADORES|CIC0099|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|CIC0210|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|CIC0211|
    |PRÁTICAS EM COMPUTAÇÃO|CIC0227|
    |PRINCÍPIOS DE VISÃO COMPUTACIONAL|CIC0195|
    |PROCESSAMENTO DE SINAIS MULTIMÍDIA|CIC0196|
    |PROCESSAMENTO EM TEMPO REAL|CIC0126|
    |PRODUÇÃO CIENTIFICA NA LICENCIATURA EM COMPUTAÇÃO|CIC0223|
    |PRODUÇÃO DE MATERIAL DIDÁTICO|CIC0208|
    |PROGRAMAÇÃO COMPETITIVA|CIC0169|
    |PROGRAMAÇÃO CONCORRENTE|CIC0202|
    |PROJETO DE LICENCIATURA|CIC0157|
    |PROJETO DE LICENCIATURA 1|CIC0163|
    |PROJETO DE LICENCIATURA 2|CIC0164|
    |PROJETO DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|CIC0224|
    |PROJETO E ANÁLISE DE ALGORITMOS|CIC0189|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 1|CIC0353|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 2|CIC0356|
    |PROJETO INTERDISCIPLINAR DE LICENCIATURA EM COMPUTAÇÃO|CIC0207|
    |REDES DE COMPUTADORES|CIC0124|
    |SEGURANÇA COMPUTACIONAL|CIC0201|
    |SINAIS E SISTEMAS|CIC0242|
    |SISTEMAS DE INFORMACAO|CIC0101|
    |SISTEMAS OPERACIONAIS|CIC0108|
    |SOFTWARE BASICO|CIC0104|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|CIC0212|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|CIC0213|
    |SUPERVISÃO DE PRODUÇÃO DE MATERIAL DIDÁTICO|CIC0209|
    |TECNICAS DE PROGRAMAÇÃO 1|CIC0197|
    |TECNICAS DE PROGRAMAÇÃO 2|CIC0198|
    |TELEINFORMÁTICA E REDES 1|CIC0235|
    |TELEINFORMÁTICA E REDES 2|CIC0236|
    |TEORIA DA COMPUTACAO|CIC0095|
    |TEORIA E APLICAÇÃO DE GRAFOS|CIC0199|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 1|CIC0155|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 2|CIC0156|
    |TOPICOS AVANCADOS EM COMPUTADORES|CIC0087|
    |TRABALHO DE GRADUAÇÃO 1|CIC0166|
    |TRABALHO DE GRADUAÇÃO 2|CIC0167|
    |TRADUTORES|CIC0106|
    |TRANSMISSÃO DE DADOS|CIC0103|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 1|CIC0218|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 2|CIC0220|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 3|CIC0222|
    |VISUALIZAÇÃO DE DADOS|CIC0352|

    E que eu coloco o arquivo "features/files/turmas_test_happy.html" em "arquivo_turmas"
    Quando eu aperto em "Importar disciplinas"
    Então eu devo estar na página de importar disciplinas
    E eu devo ver os seguintes itens somente uma vez:
    |ALGORITMOS E PROGRAMAÇÃO DE COMPUTADORES|
    |ARQUITETURA DE PROCESSADORES DIGITAIS|
    |ARQUITETURAS AVANCADAS|
    |AUTÔMATOS E COMPUTABILIDADE|
    |BANCOS DE DADOS|
    |CIRCUITOS LÓGICOS|
    |COMPUTAÇÃO EXPERIMENTAL|
    |DESENVOLVIMENTO DE APLICATIVOS|
    |ENGENHARIA DE SOFTWARE|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 1|
    |ESTÁGIO SUPERVISIONADO EM ENGENHARIA DE COMPUTAÇÃO 2|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 1|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 2|
    |ESTÁGIO SUPERVISIONADO EM LICENCIATURA EM COMPUTAÇÃO 3|
    |ESTRUTURAS DE DADOS|
    |ESTUDOS EM COMPUTACAO MULTIMIDIA|
    |ESTUDOS EM INTELIGENCIA ARTIFICIAL|
    |ESTUDOS EM SISTEMAS DE COMPUTACAO|
    |ESTUDOS EM SISTEMAS DE INFORMACAO|
    |FORMAÇÃO DOCENTE EM COMPUTAÇÃO|
    |FUNDAMENTOS TEÓRICOS DA COMPUTAÇÃO|
    |INFORMATICA APLICADA A EDUCACAO|
    |INFORMATICA E SOCIEDADE|
    |INTERAÇÃO HUMANO COMPUTADOR|
    |INTRODUÇÃO À CIÊNCIA DA COMPUTAÇÃO|
    |INTRODUÇÃO À ENGENHARIA DE COMPUTAÇÃO|
    |INTRODUCAO A INTELIGENCIA ARTIFICIAL|
    |INTRODUCAO A MICROINFORMATICA|
    |INTRODUCAO AO PROCESSAMENTO DE IMAGENS|
    |INTRODUÇÃO AOS SISTEMAS COMPUTACIONAIS|
    |INTRODUÇÃO AOS SISTEMAS EMBARCADOS|
    |INTRODUÇÃO A SISTEMAS OPERACIONAIS|
    |LABORATÓRIO DE CIRCUITOS LÓGICOS|
    |LINGUAGENS DE PROGRAMACAO|
    |LÓGICA COMPUTACIONAL 1|
    |METODOLOGIA CIENTÍFICA|
    |MÉTODOS DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|
    |MÉTODOS DE PROGRAMAÇÃO|
    |ORGANIZAÇÃO E ARQUITETURA DE COMPUTADORES|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|
    |PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|
    |PRÁTICAS EM COMPUTAÇÃO|
    |PRINCÍPIOS DE VISÃO COMPUTACIONAL|
    |PROCESSAMENTO DE SINAIS MULTIMÍDIA|
    |PROCESSAMENTO EM TEMPO REAL|
    |PRODUÇÃO CIENTIFICA NA LICENCIATURA EM COMPUTAÇÃO|
    |PRODUÇÃO DE MATERIAL DIDÁTICO|
    |PROGRAMAÇÃO COMPETITIVA|
    |PROGRAMAÇÃO CONCORRENTE|
    |PROJETO DE LICENCIATURA|
    |PROJETO DE LICENCIATURA 1|
    |PROJETO DE LICENCIATURA 2|
    |PROJETO DE PESQUISA NA LICENCIATURA EM COMPUTAÇÃO|
    |PROJETO E ANÁLISE DE ALGORITMOS|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 1|
    |PROJETO FINAL EM ENGENHARIA DE COMPUTAÇÃO 2|
    |PROJETO INTERDISCIPLINAR DE LICENCIATURA EM COMPUTAÇÃO|
    |REDES DE COMPUTADORES|
    |SEGURANÇA COMPUTACIONAL|
    |SINAIS E SISTEMAS|
    |SISTEMAS DE INFORMACAO|
    |SISTEMAS OPERACIONAIS|
    |SOFTWARE BASICO|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 1|
    |SUPERVISÃO DE PRÁTICA PEDAGÓGICA EM COMPUTAÇÃO 2|
    |SUPERVISÃO DE PRODUÇÃO DE MATERIAL DIDÁTICO|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 1|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 2|
    |SUPRVISÃO DE ESTÁGIO EM LICENCIATURA EM COMPUTAÇÃO 3|
    |TECNICAS DE PROGRAMAÇÃO 1|
    |TECNICAS DE PROGRAMAÇÃO 2|
    |TELEINFORMÁTICA E REDES 1|
    |TELEINFORMÁTICA E REDES 2|
    |TEORIA DA COMPUTACAO|
    |TEORIA E APLICAÇÃO DE GRAFOS|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 1|
    |TEORIA E PRATICA PEDAGOGICA EM INFORMATICA 2|
    |TOPICOS AVANCADOS EM COMPUTADORES|
    |TRABALHO DE GRADUAÇÃO 1|
    |TRABALHO DE GRADUAÇÃO 2|
    |TRADUTORES|
    |TRANSMISSÃO DE DADOS|
    |VISUALIZAÇÃO DE DADOS|

Cenário: Nenhum arquivo enviado
    Quando eu aperto em "Importar disciplinas"
    Então eu devo estar na página de importar disciplinas
    E eu devo ver "Por favor, selecionar um arquivo"